-- MySQL Script generated by MySQL Workbench
-- Thu Mar 15 12:47:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gastos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gastos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gastos` DEFAULT CHARACTER SET latin1 ;
USE `gastos` ;

-- -----------------------------------------------------
-- Table `gastos`.`regiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastos`.`regiones` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estatus` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gastos`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastos`.`municipios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'catalogo de municipios',
  `nombre` VARCHAR(45) NOT NULL,
  `regiones_id` INT(11) NOT NULL,
  `estatus` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_municipios_regiones1_idx` (`regiones_id` ASC),
  CONSTRAINT `fk_municipios_regiones1`
    FOREIGN KEY (`regiones_id`)
    REFERENCES `gastos`.`regiones` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gastos`.`tipos_programas_general`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastos`.`tipos_programas_general` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `estatus` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gastos`.`unidades_presupuestales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastos`.`unidades_presupuestales` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `año` INT(11) NOT NULL,
  `estatus` TINYINT(4) NOT NULL DEFAULT '1',
  `clave` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `clave_UNIQUE` (`clave` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gastos`.`unidades_responsables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastos`.`unidades_responsables` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `año` INT(11) NOT NULL,
  `estatus` TINYINT(4) NOT NULL DEFAULT '1',
  `clave` CHAR(3) NOT NULL,
  `up_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_ur_up_idx` (`up_id` ASC),
  UNIQUE INDEX `clave_UNIQUE` (`clave` ASC),
  CONSTRAINT `fk_ur_up1`
    FOREIGN KEY (`up_id`)
    REFERENCES `gastos`.`unidades_presupuestales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gastos`.`unidades_ejecutoras_gastos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastos`.`unidades_ejecutoras_gastos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `año` INT(11) NOT NULL,
  `estatus` TINYINT(4) NOT NULL DEFAULT '1',
  `clave` CHAR(5) NOT NULL,
  `ur_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_ueg_ur_idx` (`ur_id` ASC),
  UNIQUE INDEX `clave_UNIQUE` (`clave` ASC),
  CONSTRAINT `fk_ueg_ur1`
    FOREIGN KEY (`ur_id`)
    REFERENCES `gastos`.`unidades_responsables` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gastos`.`unidades_operadoras_gastos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastos`.`unidades_operadoras_gastos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `municipios_id` INT(11) NOT NULL,
  `ueg_id` INT(11) NOT NULL,
  `estatus` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_escuelas_municipios1_idx` (`municipios_id` ASC),
  INDEX `fk_escuelas_ueg1_idx` (`ueg_id` ASC),
  CONSTRAINT `fk_escuelas_municipios`
    FOREIGN KEY (`municipios_id`)
    REFERENCES `gastos`.`municipios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_escuelas_ueg1`
    FOREIGN KEY (`ueg_id`)
    REFERENCES `gastos`.`unidades_ejecutoras_gastos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gastos`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastos`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `apellido_paterno` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `apellido_materno` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `password` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `estatus` TINYINT(1) NOT NULL DEFAULT '1',
  `remember_token` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
